#!/bin/sh

repo="https://github.com/tomcodes/dotfiles.git"


# Check dependencies
check_command() {
    command -v "$1" > /dev/null 2>&1 || { echo "This init script requires the \`${1}\` binary in order to run." >&2; exit 1; }
}

check_command "git"

echo "Setting up your environment, please be patient...";

cd ~/

echo "Cloning repo from $repo"
git clone $repo

~/dotfiles/local-install
